

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_USER: champion
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: performance_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  web:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: performance_db
      DB_USER: champion
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 3306

volumes:
  mariadb_data:
